### ISSUE TITLE
Missing options in COAP response

### ISSUE THREAD

**Issue by alfiedouglas-tewke** [coapjs/node-coap#365]
I am trying to add a `Content-Format` option to my COAP response, this seems to work when the data size is below `1280`. But if it exceeds `1280` the data is received, but removes the added option. I have checked the response in wireshark and the option is there, so it must be where the packet is reconstructed on the client.

Working example with a small packet
```
CoapServer.on('request', (req: IncomingMessage, res: OutgoingMessage) => {
    const data = "a".repeat(10);
    res.code = COAP.HttpToCoapStatus(resp.status);
    res.setOption("Content-Format", 'application/cbor');
    res.end(CBOR.encode(data));
});
```
![Capture](https://github.com/coapjs/node-coap/assets/73226041/b68e1ad8-6e36-4217-ac71-504e6b188aa6)

Here I loose the `Content-Format` option on the client, see screenshot:
```
CoapServer.on('request', (req: IncomingMessage, res: OutgoingMessage) => {
    const data = "a".repeat(1300);
    res.code = COAP.HttpToCoapStatus(resp.status);
    res.setOption("Content-Format", 'application/cbor');
    res.end(CBOR.encode(data));
});
```

![Capture2](https://github.com/coapjs/node-coap/assets/73226041/f332a658-a29c-4f26-9550-15393534f1e7)

I assume this is to do with when the client receiving a blockwise transfer?

**Comment by JKRhb** [comment]
Hi @alfiedouglas-tewke, thank you for reporting this issue! I will try to look into it in the upcoming days and provide a fix as soon as possible.

**Comment by JKRhb** [comment]
Could you try out if #366 works for you as a workaround? After doing some investigation, the server-side seemed to be the cause of the problem.

**Comment by Apollon77** [comment]
@alfiedouglas-tewke An chance to verify the fix from your side?

**Comment by alfiedouglas-tewke** [comment]
Hi @JKRhb @Apollon77, thank so much for the fix! Unfortunately it did not solve the bug for me. When looking in Wireshark, the responses contain the options, so I think this is a bug on the client side?
