### ISSUE TITLE
Consider making a new release to npm.

### ISSUE THREAD

**Issue by JimmyBjorklund** [coapjs/node-coap#381]
There has bin a lot of changes and improvements, might be time for a new release ?

**Comment by JKRhb** [comment]
Thank you for the hint, @JimmyBjorklund, I think we can keep this issue open to remind us of that :)

**Comment by JKRhb** [comment]
Thanks again for the reminder, @JimmyBjorklund, we will hopefully make a new release in the next few days :) CC @Apollon77
